name: Main
on:
  - push
  - pull_request
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
    runs-on: ${{ matrix.platform }}
    env:
      PLUGIN_RUBY_CI: true
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: bundle exec rake test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      PLUGIN_RUBY_CI: true
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.0"
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn prepublishOnly
      - run: yarn checkFormat
      - run: yarn lint

  smoketest:
    name: Yarn PnP smoke test
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        yarn:
          - 2.x
          - 3.x
    runs-on: ${{ matrix.platform }}
    env:
      PLUGIN_RUBY_CI: true
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.0"
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run prepublishOnly
      - run: yarn pack
      # Windows runners don't have /tmp, let's make sure it exists
      - run: mkdir -p /tmp
      - run: mv prettier-plugin-ruby-*.tgz /tmp/prettier-plugin-ruby.tgz
      - run: mkdir /tmp/smoketest
      - name: Smoke test
        run: |
          cd /tmp/smoketest
          echo '{ "name": "smoketest" }' > package.json
          yarn set version berry # workaround for https://github.com/yarnpkg/berry/issues/3180
          yarn set version ${{ matrix.yarn }}
          yarn add prettier @prettier/plugin-ruby@file:/tmp/prettier-plugin-ruby.tgz
          npx rimraf .yarn/unplugged # Make sure Yarn didn't unplug anything; this will deliberately break if it did
          echo '{ "plugins": ["@prettier/plugin-ruby"] }' >.prettierrc.json
          echo 'def add(a, b) ; a + b ; end' >smoketest.rb
          yarn run prettier -w smoketest.rb
          ruby -c smoketest.rb

  gem:
    name: Gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.0"
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn prepublishOnly
      - run: gem build -o prettier.gem
      - run: gem unpack prettier.gem
      - run: prettier/exe/rbprettier --help

  # Saves pull request details for later workflow runs which can run in
  # a privileged environment
  save-pr-info:
    name: Save PR info
    needs:
      - ci
      - lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Save PR number
        run: |
          mkdir -p ./save-pr-info
          echo ${{ github.event.number }} > ./save-pr-info/PULL_REQUEST_NUMBER
      - uses: actions/upload-artifact@v2
        with:
          name: save-pr-info
          path: save-pr-info/
